name: kamera_mantap

description: "A new Flutter project using camera."

publish_to: 'none' # Hanya untuk proyek lokal, hapus jika ingin dipublikasikan

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8  # Ikon untuk iOS
  camera: ^0.11.1          # Plugin kamera
  path_provider: ^2.1.5    # Mengelola path file di perangkat
  path: ^1.9.0             # Manipulasi path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
